webtalk_init -webtalk_dir /home/muqdas_satti/Desktop/Verilog/counter16/16bit_counter/16bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_16bit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb  8 10:23:09 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5067e463-4016-43db-b447-c6edc6e58665" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8df14c911a9f4676b86be57cfaed1c29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 24.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "799.984 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "25.79_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116788_KB" -context "xsim\\usage"
webtalk_transmit -clientid 341900790 -regid "" -xml /home/muqdas_satti/Desktop/Verilog/counter16/16bit_counter/16bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_16bit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/muqdas_satti/Desktop/Verilog/counter16/16bit_counter/16bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_16bit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/muqdas_satti/Desktop/Verilog/counter16/16bit_counter/16bit_counter.sim/sim_1/behav/xsim/xsim.dir/counter_16bit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
