#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 08 10:09:37 PKT 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim counter_16bit_tb_behav -key {Behavioral:sim_1:Functional:counter_16bit_tb} -tclbatch counter_16bit_tb.tcl -view /home/muqdas_satti/Desktop/Verilog/counter16/16bit_counter/counter_16bit_tb_behav.wcfg -log simulate.log"
xsim counter_16bit_tb_behav -key {Behavioral:sim_1:Functional:counter_16bit_tb} -tclbatch counter_16bit_tb.tcl -view /home/muqdas_satti/Desktop/Verilog/counter16/16bit_counter/counter_16bit_tb_behav.wcfg -log simulate.log

